// Code generated by protoc-gen-go.
// source: descriptor.proto
// DO NOT EDIT!

/*
Package descriptor is a generated protocol buffer package.

It is generated from these files:
	descriptor.proto

It has these top-level messages:
	StructDescriptor
	FieldDescriptor
	ImportResult
	ExportRequest
*/
package descriptor

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type TypeEnum int32

const (
	TypeEnum_Unknown  TypeEnum = 0
	TypeEnum_Nil      TypeEnum = 1
	TypeEnum_Bool     TypeEnum = 2
	TypeEnum_Int8     TypeEnum = 3
	TypeEnum_Uint8    TypeEnum = 4
	TypeEnum_Int16    TypeEnum = 5
	TypeEnum_Uint16   TypeEnum = 6
	TypeEnum_Int32    TypeEnum = 7
	TypeEnum_Uint32   TypeEnum = 8
	TypeEnum_Int64    TypeEnum = 9
	TypeEnum_Uint64   TypeEnum = 10
	TypeEnum_Float32  TypeEnum = 11
	TypeEnum_Float64  TypeEnum = 12
	TypeEnum_String   TypeEnum = 13
	TypeEnum_Bytes    TypeEnum = 14
	TypeEnum_DateTime TypeEnum = 15
)

var TypeEnum_name = map[int32]string{
	0:  "Unknown",
	1:  "Nil",
	2:  "Bool",
	3:  "Int8",
	4:  "Uint8",
	5:  "Int16",
	6:  "Uint16",
	7:  "Int32",
	8:  "Uint32",
	9:  "Int64",
	10: "Uint64",
	11: "Float32",
	12: "Float64",
	13: "String",
	14: "Bytes",
	15: "DateTime",
}
var TypeEnum_value = map[string]int32{
	"Unknown":  0,
	"Nil":      1,
	"Bool":     2,
	"Int8":     3,
	"Uint8":    4,
	"Int16":    5,
	"Uint16":   6,
	"Int32":    7,
	"Uint32":   8,
	"Int64":    9,
	"Uint64":   10,
	"Float32":  11,
	"Float64":  12,
	"String":   13,
	"Bytes":    14,
	"DateTime": 15,
}

func (x TypeEnum) String() string {
	return proto.EnumName(TypeEnum_name, int32(x))
}

type StructDescriptor struct {
	Name          string             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CamelCaseName string             `protobuf:"bytes,2,opt,name=camel_case_name" json:"camel_case_name,omitempty"`
	Comment       string             `protobuf:"bytes,3,opt,name=comment" json:"comment,omitempty"`
	Fields        []*FieldDescriptor `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	Options       map[string]string  `protobuf:"bytes,5,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *StructDescriptor) Reset()         { *m = StructDescriptor{} }
func (m *StructDescriptor) String() string { return proto.CompactTextString(m) }
func (*StructDescriptor) ProtoMessage()    {}

func (m *StructDescriptor) GetFields() []*FieldDescriptor {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *StructDescriptor) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

type FieldDescriptor struct {
	Name             string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CamelCaseName    string            `protobuf:"bytes,2,opt,name=camel_case_name" json:"camel_case_name,omitempty"`
	Type             TypeEnum          `protobuf:"varint,3,opt,name=type,enum=descriptor.TypeEnum" json:"type,omitempty"`
	TypeName         string            `protobuf:"bytes,4,opt,name=type_name" json:"type_name,omitempty"`
	OriginalTypeName string            `protobuf:"bytes,5,opt,name=original_type_name" json:"original_type_name,omitempty"`
	Comment          string            `protobuf:"bytes,6,opt,name=comment" json:"comment,omitempty"`
	DefaultValue     string            `protobuf:"bytes,7,opt,name=default_value" json:"default_value,omitempty"`
	Options          map[string]string `protobuf:"bytes,8,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FieldDescriptor) Reset()         { *m = FieldDescriptor{} }
func (m *FieldDescriptor) String() string { return proto.CompactTextString(m) }
func (*FieldDescriptor) ProtoMessage()    {}

func (m *FieldDescriptor) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

type ImportResult struct {
	Version     string              `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Comment     string              `protobuf:"bytes,2,opt,name=comment" json:"comment,omitempty"`
	Timestamp   string              `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Descriptors []*StructDescriptor `protobuf:"bytes,4,rep,name=descriptors" json:"descriptors,omitempty"`
}

func (m *ImportResult) Reset()         { *m = ImportResult{} }
func (m *ImportResult) String() string { return proto.CompactTextString(m) }
func (*ImportResult) ProtoMessage()    {}

func (m *ImportResult) GetDescriptors() []*StructDescriptor {
	if m != nil {
		return m.Descriptors
	}
	return nil
}

type ExportRequest struct {
	Version  string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Format   string `protobuf:"bytes,3,opt,name=format" json:"format,omitempty"`
	Filepath string `protobuf:"bytes,4,opt,name=filepath" json:"filepath,omitempty"`
	Args     string `protobuf:"bytes,5,opt,name=args" json:"args,omitempty"`
}

func (m *ExportRequest) Reset()         { *m = ExportRequest{} }
func (m *ExportRequest) String() string { return proto.CompactTextString(m) }
func (*ExportRequest) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("descriptor.TypeEnum", TypeEnum_name, TypeEnum_value)
}
